version: '3'

services:
  astawash-app:
    build: .
    image: astawash-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    env_file:
      - astawash.env
    expose:
      - 3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/astawash-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  nginx:
    image: nginx:stable-alpine3.17-slim
    build:
      context: ./ngnix
    ports:
      - 80:80
    volumes:
      - ./ngnix:/etc/nginx/conf.d/

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
